name: Full Stack App Core Setup
on: [push]
jobs:
  linter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      
      - name: Install packages
        run: |
            npm install
            cd client && npm install && cd client
      
      - name: Linting
        run: npm run lint